"""add flag to user_session

Revision ID: f2d2b502308e
Revises: d715788437a1
Create Date: 2026-05-08 14:06:25.998461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2d2b502308e'
down_revision: Union[str, Sequence[str], None] = 'd715788437a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_status_id'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_user_sessions_u_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_us_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_users_u_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('u_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('u_username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('u_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('u_id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_u_id'), 'users', ['u_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('us_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('us_jwt_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('us_refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['users.u_id'], name=op.f('user_sessions_u_id_fkey')),
    sa.PrimaryKeyConstraint('us_id', name=op.f('user_sessions_pkey'))
    )
    op.create_index(op.f('ix_user_sessions_us_id'), 'user_sessions', ['us_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_u_id'), 'user_sessions', ['u_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('status_pkey'))
    )
    op.create_index(op.f('ix_status_id'), 'status', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    # ### end Alembic commands ###
